sudo: false
language: java
java:
- openjdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - gradle generatePomFileForMavenPublication
deploy:
  provider: bintray
  file: descriptor.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY